version: "3.9"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "52000:52000"
    environment:
      - NODE_ENV=production
      - BRIDGE_IP=${BRIDGE_IP}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - DATABASE_URL=file:/data/app.db
      - CERT_PATH=${CERT_PATH}
    volumes:
      - ./db:/data

  processor:
    build:
      context: ./
      dockerfile: ./processor/Dockerfile
    environment:
      - DATABASE_URL=file:/data/app.db
    volumes:
      - ./db:/data
    depends_on:
      - web
