import type React from 'next';
import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import { Refresh } from './_components/Refresh';
import { KidsModeProvider } from './_context/KidsModeContext';
import { ToggleKidsMode } from './_components/ToggleKidsMode';
import { Title } from './_components/Title';

const defaultFont = Noto_Sans_JP({
  subsets: ['latin'],
  weight: '400',
});

const title = 'お薬飲んでないとブチギレるゾ';

export const metadata: Metadata = {
  title,
  description: 'Generated by create next app',
  manifest: '/public/manifest.json',
  icons: {
    apple: '/icon512_maskable.png',
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja" className="font-bold text-slate-700">
      <body className={`${defaultFont.className} flex min-h-screen flex-col antialiased`}>
        <KidsModeProvider>
          <Refresh />
          <Title />
          <ToggleKidsMode />
          {children}
        </KidsModeProvider>
      </body>
    </html>
  );
}
